"""Static language catalog for UI multi-selects."""

LANGUAGES: list[dict[str, str]] = [
    {"code": "vi", "name": "Vietnamese", "native": "Tiếng Việt"},
    {"code": "en", "name": "English", "native": "English"},
    {"code": "ja", "name": "Japanese", "native": "日本語"},
    {"code": "ko", "name": "Korean", "native": "한국어"},
    {"code": "zh", "name": "Chinese (Simplified)", "native": "简体中文"},
    {"code": "zh-TW", "name": "Chinese (Traditional)", "native": "繁體中文"},
    {"code": "fr", "name": "French", "native": "Français"},
    {"code": "de", "name": "German", "native": "Deutsch"},
    {"code": "es", "name": "Spanish", "native": "Español"},
    {"code": "pt", "name": "Portuguese", "native": "Português"},
    {"code": "pt-BR", "name": "Portuguese (Brazil)", "native": "Português (Brasil)"},
    {"code": "it", "name": "Italian", "native": "Italiano"},
    {"code": "ru", "name": "Russian", "native": "Русский"},
    {"code": "ar", "name": "Arabic", "native": "العربية"},
    {"code": "th", "name": "Thai", "native": "ไทย"},
    {"code": "id", "name": "Indonesian", "native": "Bahasa Indonesia"},
    {"code": "ms", "name": "Malay", "native": "Bahasa Melayu"},
    {"code": "hi", "name": "Hindi", "native": "हिन्दी"},
    {"code": "tr", "name": "Turkish", "native": "Türkçe"},
    {"code": "nl", "name": "Dutch", "native": "Nederlands"},
    {"code": "pl", "name": "Polish", "native": "Polski"},
    {"code": "sv", "name": "Swedish", "native": "Svenska"},
    {"code": "da", "name": "Danish", "native": "Dansk"},
    {"code": "fi", "name": "Finnish", "native": "Suomi"},
    {"code": "no", "name": "Norwegian", "native": "Norsk"},
    {"code": "cs", "name": "Czech", "native": "Čeština"},
    {"code": "ro", "name": "Romanian", "native": "Română"},
    {"code": "uk", "name": "Ukrainian", "native": "Українська"},
    {"code": "he", "name": "Hebrew", "native": "עברית"},
    {"code": "el", "name": "Greek", "native": "Ελληνικά"},
]
