/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdActivityRouteImport } from './routes/projects/$projectId/activity'
import { Route as ProjectsProjectIdImportExportRouteImport } from './routes/projects/$projectId/import-export'
import { Route as ProjectsProjectIdModulesRouteImport } from './routes/projects/$projectId/modules'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdStringsRouteImport } from './routes/projects/$projectId/strings'
import { Route as ProjectsProjectIdTagsRouteImport } from './routes/projects/$projectId/tags'
import { Route as ProjectsProjectIdVersionsRouteImport } from './routes/projects/$projectId/versions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdActivityRoute =
  ProjectsProjectIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdImportExportRoute =
  ProjectsProjectIdImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdModulesRoute =
  ProjectsProjectIdModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdStringsRoute =
  ProjectsProjectIdStringsRouteImport.update({
    id: '/strings',
    path: '/strings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTagsRoute = ProjectsProjectIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdVersionsRoute =
  ProjectsProjectIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/activity': typeof ProjectsProjectIdActivityRoute
  '/projects/$projectId/import-export': typeof ProjectsProjectIdImportExportRoute
  '/projects/$projectId/modules': typeof ProjectsProjectIdModulesRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/strings': typeof ProjectsProjectIdStringsRoute
  '/projects/$projectId/tags': typeof ProjectsProjectIdTagsRoute
  '/projects/$projectId/versions': typeof ProjectsProjectIdVersionsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/activity': typeof ProjectsProjectIdActivityRoute
  '/projects/$projectId/import-export': typeof ProjectsProjectIdImportExportRoute
  '/projects/$projectId/modules': typeof ProjectsProjectIdModulesRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/strings': typeof ProjectsProjectIdStringsRoute
  '/projects/$projectId/tags': typeof ProjectsProjectIdTagsRoute
  '/projects/$projectId/versions': typeof ProjectsProjectIdVersionsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/activity': typeof ProjectsProjectIdActivityRoute
  '/projects/$projectId/import-export': typeof ProjectsProjectIdImportExportRoute
  '/projects/$projectId/modules': typeof ProjectsProjectIdModulesRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/strings': typeof ProjectsProjectIdStringsRoute
  '/projects/$projectId/tags': typeof ProjectsProjectIdTagsRoute
  '/projects/$projectId/versions': typeof ProjectsProjectIdVersionsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/import-export'
    | '/projects/$projectId/modules'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/strings'
    | '/projects/$projectId/tags'
    | '/projects/$projectId/versions'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/projects/new'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/import-export'
    | '/projects/$projectId/modules'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/strings'
    | '/projects/$projectId/tags'
    | '/projects/$projectId/versions'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/import-export'
    | '/projects/$projectId/modules'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/strings'
    | '/projects/$projectId/tags'
    | '/projects/$projectId/versions'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/activity': {
      id: '/projects/$projectId/activity'
      path: '/activity'
      fullPath: '/projects/$projectId/activity'
      preLoaderRoute: typeof ProjectsProjectIdActivityRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/import-export': {
      id: '/projects/$projectId/import-export'
      path: '/import-export'
      fullPath: '/projects/$projectId/import-export'
      preLoaderRoute: typeof ProjectsProjectIdImportExportRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/modules': {
      id: '/projects/$projectId/modules'
      path: '/modules'
      fullPath: '/projects/$projectId/modules'
      preLoaderRoute: typeof ProjectsProjectIdModulesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/strings': {
      id: '/projects/$projectId/strings'
      path: '/strings'
      fullPath: '/projects/$projectId/strings'
      preLoaderRoute: typeof ProjectsProjectIdStringsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tags': {
      id: '/projects/$projectId/tags'
      path: '/tags'
      fullPath: '/projects/$projectId/tags'
      preLoaderRoute: typeof ProjectsProjectIdTagsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/versions': {
      id: '/projects/$projectId/versions'
      path: '/versions'
      fullPath: '/projects/$projectId/versions'
      preLoaderRoute: typeof ProjectsProjectIdVersionsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdActivityRoute: typeof ProjectsProjectIdActivityRoute
  ProjectsProjectIdImportExportRoute: typeof ProjectsProjectIdImportExportRoute
  ProjectsProjectIdModulesRoute: typeof ProjectsProjectIdModulesRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdStringsRoute: typeof ProjectsProjectIdStringsRoute
  ProjectsProjectIdTagsRoute: typeof ProjectsProjectIdTagsRoute
  ProjectsProjectIdVersionsRoute: typeof ProjectsProjectIdVersionsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdActivityRoute: ProjectsProjectIdActivityRoute,
  ProjectsProjectIdImportExportRoute: ProjectsProjectIdImportExportRoute,
  ProjectsProjectIdModulesRoute: ProjectsProjectIdModulesRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdStringsRoute: ProjectsProjectIdStringsRoute,
  ProjectsProjectIdTagsRoute: ProjectsProjectIdTagsRoute,
  ProjectsProjectIdVersionsRoute: ProjectsProjectIdVersionsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
