/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsProjectRefRouteImport } from './routes/projects/$projectRef'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectRefIndexRouteImport } from './routes/projects/$projectRef/index'
import { Route as ProjectsProjectRefActivityRouteImport } from './routes/projects/$projectRef/activity'
import { Route as ProjectsProjectRefImportExportRouteImport } from './routes/projects/$projectRef/import-export'
import { Route as ProjectsProjectRefModulesRouteImport } from './routes/projects/$projectRef/modules'
import { Route as ProjectsProjectRefSettingsRouteImport } from './routes/projects/$projectRef/settings'
import { Route as ProjectsProjectRefStringsRouteImport } from './routes/projects/$projectRef/strings'
import { Route as ProjectsProjectRefTagsRouteImport } from './routes/projects/$projectRef/tags'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectRefRoute = ProjectsProjectRefRouteImport.update({
  id: '/projects/$projectRef',
  path: '/projects/$projectRef',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectRefIndexRoute = ProjectsProjectRefIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectRefRoute,
} as any)
const ProjectsProjectRefActivityRoute =
  ProjectsProjectRefActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ProjectsProjectRefRoute,
  } as any)
const ProjectsProjectRefImportExportRoute =
  ProjectsProjectRefImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => ProjectsProjectRefRoute,
  } as any)
const ProjectsProjectRefModulesRoute =
  ProjectsProjectRefModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => ProjectsProjectRefRoute,
  } as any)
const ProjectsProjectRefSettingsRoute =
  ProjectsProjectRefSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectRefRoute,
  } as any)
const ProjectsProjectRefStringsRoute =
  ProjectsProjectRefStringsRouteImport.update({
    id: '/strings',
    path: '/strings',
    getParentRoute: () => ProjectsProjectRefRoute,
  } as any)
const ProjectsProjectRefTagsRoute = ProjectsProjectRefTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ProjectsProjectRefRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/$projectRef': typeof ProjectsProjectRefRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectRef/activity': typeof ProjectsProjectRefActivityRoute
  '/projects/$projectRef/import-export': typeof ProjectsProjectRefImportExportRoute
  '/projects/$projectRef/modules': typeof ProjectsProjectRefModulesRoute
  '/projects/$projectRef/settings': typeof ProjectsProjectRefSettingsRoute
  '/projects/$projectRef/strings': typeof ProjectsProjectRefStringsRoute
  '/projects/$projectRef/tags': typeof ProjectsProjectRefTagsRoute
  '/projects/$projectRef/': typeof ProjectsProjectRefIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectRef/activity': typeof ProjectsProjectRefActivityRoute
  '/projects/$projectRef/import-export': typeof ProjectsProjectRefImportExportRoute
  '/projects/$projectRef/modules': typeof ProjectsProjectRefModulesRoute
  '/projects/$projectRef/settings': typeof ProjectsProjectRefSettingsRoute
  '/projects/$projectRef/strings': typeof ProjectsProjectRefStringsRoute
  '/projects/$projectRef/tags': typeof ProjectsProjectRefTagsRoute
  '/projects/$projectRef': typeof ProjectsProjectRefIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/$projectRef': typeof ProjectsProjectRefRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectRef/activity': typeof ProjectsProjectRefActivityRoute
  '/projects/$projectRef/import-export': typeof ProjectsProjectRefImportExportRoute
  '/projects/$projectRef/modules': typeof ProjectsProjectRefModulesRoute
  '/projects/$projectRef/settings': typeof ProjectsProjectRefSettingsRoute
  '/projects/$projectRef/strings': typeof ProjectsProjectRefStringsRoute
  '/projects/$projectRef/tags': typeof ProjectsProjectRefTagsRoute
  '/projects/$projectRef/': typeof ProjectsProjectRefIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects/$projectRef'
    | '/projects/new'
    | '/projects/$projectRef/activity'
    | '/projects/$projectRef/import-export'
    | '/projects/$projectRef/modules'
    | '/projects/$projectRef/settings'
    | '/projects/$projectRef/strings'
    | '/projects/$projectRef/tags'
    | '/projects/$projectRef/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/projects/new'
    | '/projects/$projectRef/activity'
    | '/projects/$projectRef/import-export'
    | '/projects/$projectRef/modules'
    | '/projects/$projectRef/settings'
    | '/projects/$projectRef/strings'
    | '/projects/$projectRef/tags'
    | '/projects/$projectRef'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/projects/$projectRef'
    | '/projects/new'
    | '/projects/$projectRef/activity'
    | '/projects/$projectRef/import-export'
    | '/projects/$projectRef/modules'
    | '/projects/$projectRef/settings'
    | '/projects/$projectRef/strings'
    | '/projects/$projectRef/tags'
    | '/projects/$projectRef/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjectsProjectRefRoute: typeof ProjectsProjectRefRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectRef': {
      id: '/projects/$projectRef'
      path: '/projects/$projectRef'
      fullPath: '/projects/$projectRef'
      preLoaderRoute: typeof ProjectsProjectRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectRef/': {
      id: '/projects/$projectRef/'
      path: '/'
      fullPath: '/projects/$projectRef/'
      preLoaderRoute: typeof ProjectsProjectRefIndexRouteImport
      parentRoute: typeof ProjectsProjectRefRoute
    }
    '/projects/$projectRef/activity': {
      id: '/projects/$projectRef/activity'
      path: '/activity'
      fullPath: '/projects/$projectRef/activity'
      preLoaderRoute: typeof ProjectsProjectRefActivityRouteImport
      parentRoute: typeof ProjectsProjectRefRoute
    }
    '/projects/$projectRef/import-export': {
      id: '/projects/$projectRef/import-export'
      path: '/import-export'
      fullPath: '/projects/$projectRef/import-export'
      preLoaderRoute: typeof ProjectsProjectRefImportExportRouteImport
      parentRoute: typeof ProjectsProjectRefRoute
    }
    '/projects/$projectRef/modules': {
      id: '/projects/$projectRef/modules'
      path: '/modules'
      fullPath: '/projects/$projectRef/modules'
      preLoaderRoute: typeof ProjectsProjectRefModulesRouteImport
      parentRoute: typeof ProjectsProjectRefRoute
    }
    '/projects/$projectRef/settings': {
      id: '/projects/$projectRef/settings'
      path: '/settings'
      fullPath: '/projects/$projectRef/settings'
      preLoaderRoute: typeof ProjectsProjectRefSettingsRouteImport
      parentRoute: typeof ProjectsProjectRefRoute
    }
    '/projects/$projectRef/strings': {
      id: '/projects/$projectRef/strings'
      path: '/strings'
      fullPath: '/projects/$projectRef/strings'
      preLoaderRoute: typeof ProjectsProjectRefStringsRouteImport
      parentRoute: typeof ProjectsProjectRefRoute
    }
    '/projects/$projectRef/tags': {
      id: '/projects/$projectRef/tags'
      path: '/tags'
      fullPath: '/projects/$projectRef/tags'
      preLoaderRoute: typeof ProjectsProjectRefTagsRouteImport
      parentRoute: typeof ProjectsProjectRefRoute
    }
  }
}

interface ProjectsProjectRefRouteChildren {
  ProjectsProjectRefActivityRoute: typeof ProjectsProjectRefActivityRoute
  ProjectsProjectRefImportExportRoute: typeof ProjectsProjectRefImportExportRoute
  ProjectsProjectRefModulesRoute: typeof ProjectsProjectRefModulesRoute
  ProjectsProjectRefSettingsRoute: typeof ProjectsProjectRefSettingsRoute
  ProjectsProjectRefStringsRoute: typeof ProjectsProjectRefStringsRoute
  ProjectsProjectRefTagsRoute: typeof ProjectsProjectRefTagsRoute
  ProjectsProjectRefIndexRoute: typeof ProjectsProjectRefIndexRoute
}

const ProjectsProjectRefRouteChildren: ProjectsProjectRefRouteChildren = {
  ProjectsProjectRefActivityRoute: ProjectsProjectRefActivityRoute,
  ProjectsProjectRefImportExportRoute: ProjectsProjectRefImportExportRoute,
  ProjectsProjectRefModulesRoute: ProjectsProjectRefModulesRoute,
  ProjectsProjectRefSettingsRoute: ProjectsProjectRefSettingsRoute,
  ProjectsProjectRefStringsRoute: ProjectsProjectRefStringsRoute,
  ProjectsProjectRefTagsRoute: ProjectsProjectRefTagsRoute,
  ProjectsProjectRefIndexRoute: ProjectsProjectRefIndexRoute,
}

const ProjectsProjectRefRouteWithChildren =
  ProjectsProjectRefRoute._addFileChildren(ProjectsProjectRefRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjectsProjectRefRoute: ProjectsProjectRefRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
